@startuml

object Ship {
  shipName = "Titanic"
  yearBuilt = "March31st,1909"
}

object CruiseShip {
  shipName = "MVGemini"
  yearBuilt = "May30th,1991"
  maxNumberPassengers = 100
}

object CargoShip {
  shipName = "EverGiven"
  yearBuilt = "September25th,2018"
  cargoCapacityInTonnage = 220940
}

Ship <|-- CargoShip : is-a
Ship <|-- CruiseShip : is-a
@enduml


